export const APUESTAS_TIPO_QUINIELA = {
    MARCADOR_EXACTO: 'marcador_exacto',
    PRIMERO_EN_MARCAR: 'primero_en_marcar',
    RESULTADO_GENERAL: 'resultado_general',
    MUMERO_DE_GOL: 'numero_de_gol',
    DIFERENCIA_DE_GOL: 'diferencia_de_gol',
    RANGO_RESULTADO: 'rango_resultado',
}

export const REPARTICION_PREMIOS = {
    GANADOR_UNICO: 'ganador_unico',
    DISTRIBUCION_PROPORCIONAL: 'distribucion_proporcional',
    PREDICCION_EXACTA: 'prediccion_exacta',
    ACUMULACION: 'acumulacion',
    REPARTICION_IGUALITARIA: 'reparticion_igualitaria',
}